### ISSUE TITLE
Feature Request: Support for "Selling Right Now" tracks

### ISSUE THREAD

**Issue by aardvarkk** [AFlowOfCode/bandcamp-streamer#2]
I was hoping this extension would be able to play tracks from the "Selling Right Now" section on Bandcamp's homepage, but it looks like maybe that's not supported? I feel like given this extension's existing functionality it probably wouldn't be too hard to add? My problem with the "Feed" play is that it kind of relies on me already having set up specific musical tastes, whereas I'd like to explore more into other genres I don't normally listen to. I think it would be fun to just load up things that are selling now and give a listen to what other people are buying!

Or perhaps I'm missing something and this is already possible?

Regardless, thanks for your work!

**Comment by AFlowOfCode** [comment]
That section doesn't have any data needed for playing tracks, it's just a rapidly changing feed of album art & titles w/ links to the album page. I agree it would be cool but it's not feasible, whereas the main pages supported by this extension provide immediately usable track data since they're meant for playing audio (no need to spend any time crawling the site via ajax in order to find track data).

If you follow fans (vs artists or labels), what they are buying at that moment shows up playable in your feed playlist. It's basically your own personal "selling right now" section. I suggest if you want an unpredictable assortment of music showing up in your feed, click on 10 - 20 random albums that pop up in the "selling right now" section, go to the profile pages of 5 - 10 fans who you can see have purchased each one and follow them. Your feed will be all over the place with tons of music you've never heard in no time. If you follow a couple hundred fans this way, most likely you'll never have heard 99.9% of what shows up there. It's more like setting up a set of curators than your own music taste specifically. In my opinion that's the cool thing about the feed page, following what other people are buying.

Fyi adding other sections like tag pages, "new & notable", etc has been on my list for a while, but bandcamp handles each one differently so it's more complicated than it seems.
